logging:
  level:
    '[org.atmosphere]': warn
spring:
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3
          temperature: 0.7
    # vectorstore:
    #   pgvector:
    #     initialize-schema: true
vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.example.application

ollama:
  host: http://localhost:11434
  embed-path: /api/embeddings
  embed-model-name: nomic-embed-text